import MetaNews from "./content/metaNews";

export const Projects = [
    {
        key: 0,
        number: "000",
        name: "Project 0",
        description: "Project 0 description",
        purview: ["Project 0 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project0',
        media: 0,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 1,
        number: "001",
        name: "Project 1",
        description: "Project 1 description",
        purview: ["Project 1 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project1',
        media: 1,
        banner: 3,
        content: <MetaNews />
    },
    {
        key: 2,
        number: "002",
        name: "Project 2",
        description: "Project 2 description",
        purview: ["Project 2 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project2',
        media: 2,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 3,
        number: "003",
        name: "Project 3",
        description: "Project 3 description",
        purview: ["Project 3 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project3',
        media: 3,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 4,
        number: "004",
        name: "Project 4",
        description: "Project 4 description",
        purview: ["Project 4 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project4',
        media: 2,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 5,
        number: "005",
        name: "Project 5",
        description: "Project 5 description",
        purview: ["Project 5 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project5',
        media: 0,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 6,
        number: "006",
        name: "Project 6",
        description: "Project 6 description",
        purview: ["Project 6 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project6',
        media: 1,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 7,
        number: "007",
        name: "Project 7",
        description: "Project 7 description",
        purview: ["Project 7 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project7',
        media: 2,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 8,
        number: "008",
        name: "Project 8",
        description: "Project 8 description",
        purview: ["Project 8 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project8',
        media: 3,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 9,
        number: "009",
        name: "Project 9",
        description: "Project 9 description",
        purview: ["Project 9 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project9',
        media: 2,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 10,
        number: "010",
        name: "Project 10",
        description: "Project 10 description",
        purview: ["Project 10 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project10',
        media: 0,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 11,
        number: "011",
        name: "Project 11",
        description: "Project 11 description",
        purview: ["Project 11 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project11',
        media: 1,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 12,
        number: "012",
        name: "Project 12",
        description: "Project 12 description",
        purview: ["Project 12 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project12',
        media: 2,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 13,
        number: "013",
        name: "Project 13",
        description: "Project 13 description",
        purview: ["Project 13 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project13',
        media: 2,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 14,
        number: "014",
        name: "Project 14",
        description: "Project 14 description",
        purview: ["Project 14 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project14',
        media: 3,
        banner: 0,
        content: <MetaNews />
    },
    {
        key: 15,
        number: "015",
        name: "Project 15",
        description: "Project 15 description",
        purview: ["Project 15 UI design", "Web design", "Prototyper"],
        company: "Meta",
        href: '/project15',
        media: 2,
        banner: 0,
        content: <MetaNews />
    },
] 